### ISSUE TITLE
[Предложение] Добавить перемтоку в всплывающем окне видео

### ISSUE THREAD

**Issue by MajorPayne36** [PavelShar/anilibrix#66]
При использовании кнопки переноса видео на всплывающее маленькое окно, предлагаю добавить возможность управления видео и звука. На данный момент только стоп\плей и возврат окна. Неудобно например перемотать видео или пропустить заставку.

Также хотелось бы увидеть синхронизацию просмотренных аниме с мобильным приложением, не только синхронизацию избранных.

Также хотелось бы увидеть закладки типа буду смотреть/брошено/просмотренно/смотрю

Успехов и всего наилучшего. С уважением, Майор Пэйн (чу-чууу)

**Comment by pavloniym** [comment]
Добрый день
Предложения хорошие, но пока нет возможности добавить этот функционал, т.к. разработка этого проекта по-факту заморожена — все мои силы брошены на основную работу + на другие проекты АниЛибрии.
Есть альтернатива в виде доработанной версии от [AnimeCoder](https://t.me/anilibrixUnoffical), возможно там этот функционал будет реализован.
Спасибо за внимание к проекту!
